### ISSUE TITLE
LDmatrix issue

### ISSUE THREAD

**Issue by s041629** [CBIIT/LDlinkR#10]
Hello,

the vignette for LDmatrix states that 2-1000 SNPs can be provided, however when I provide a list with more than 100 rsIDs, the output is a data.frame with only 100 rows and 100 columns. Can this be fixed?

thank you!

**Comment by timyers** [comment]
Thank you for letting us know.  This is an error.  A maximum of 300 variant RS numbers should be permitted for LDmatrix.

**Comment by s041629** [comment]
sorry, it was a problem from my part, I have solved it. It works with 1000 variants and returns an error if >1000 variants are provided

Thank you!

**Comment by timyers** [comment]
Ok, good to know.  Thanks!
