### ISSUE TITLE
LDproxy_batch returns empty object

### ISSUE THREAD

**Issue by frahimov** [CBIIT/LDlinkR#11]
First, let me thank you for such a fantastic R package. The "LDproxy_batch" function returns an empty object.  I requested a API token, which worked with the LDproxy function. I followed the examples from the Vignette too with no luck.

snps <- c("rs3", "rs4") # here I used real SNP rs numbers
LDproxy_batch(snp = snps,  pop = "EUR",  r2d = "r2",  token = "my_token",  append = FALSE)

I see "LDlink server is working..." for each queried SNP too.
Is there anything else I am expected  to do in order to run "LDproxy_batch" besides what's shown above?

**Comment by timyers** [comment]
Thank you for your interest in LDlinkR.  It's always good to hear from users of our package.
The `LDproxy_batch` function does not return an object.  Instead, it saves the data as text files in the current working directory.  I attempted the function call as presented in the issue you opened and found the expected text files, one file for each query SNP, in the working directory.  Please let me know if this is not happening for you.
Thank you for bringing this issue to our attention.  Once the files are saved, we should display a message indicating the location of the saved files.  We can keep this issue open to remind us to include that in the next version.

**Comment by frahimov** [comment]
Thank you for your quick response and looking into this! Yes, I can see the text files in the working directory. I should have checked the working directory before opening a ticket. However, a message that displays the location of the saved files would be helpful. Currently the  LDproxy_batch function returns a NULL "object"  in the Environment, and I thought it was not working as expected.

**Comment by timyers** [comment]
Thank you for opening the issue.  Adding a message that displays the location of files will improve LDlinkR.  
Funny though but I am not seeing a NULL "object" in my environment after calling LDproxy_batch.  I'll look into that more as well.  Thanks again!

**Comment by frahimov** [comment]
It returns that NULL object because I keep assigning the output from the LDproxy_batch function to a named object. Obviously the function is supposed to run without any assignments. All clear now. Many thanks.
