### ISSUE TITLE
LDhap valid input check fails

### ISSUE THREAD

**Issue by s-rashmi** [CBIIT/LDlinkR#14]
Hi, just a minor issue!
I had given a list of 100 SNPs for LDhap function. The output received was
`Error in data_out2[1, ] : incorrect number of dimensions
`
Couldn't figure out. So I ran the LDhap.R code from github separately and got the error message from the website "error: Maximum variant list is 30 RS numbers or coordinates".

I believe one more set of outer brackets is required here at line 94 --> `if( !(length(snps) > 1) & (length(snps) <=30) ){`

Thanks a lot!

**Comment by timyers** [comment]
Thank you, Rashmi.  I'll fix that.  I'm currently in the middle of updating LDhap to include your suggestion from issue #13.  The new update will have an option to include genomic coordinates.  I'm almost ready to push the updates to Github.
Thanks for your contributions!
Regards,
T

**Comment by timyers** [comment]
Fixed issue.  Changes uploaded to dev version on Github and will be included in the next submission to CRAN.

**Comment by s-rashmi** [comment]
Thanks a lot Tim :)
