### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by frahimov** [CBIIT/LDlinkR#15]
Hi again,
I wanted to inquiry about the speed of LDlinkR. I have a list of >9,000 SNPs that I would like to pull all LD variants in EUR with these 9000 SNPs, however the speed seems very slow. It took about 1hr 20min to process 100 query SNPs. Is this speed normal? Are there options that may speed up the process a little? For example pulling SNPs above a certain r2 threshold?
Thank you

**Comment by timyers** [comment]
Hello,
Thank you for bringing this to our attention.  After looking into this, we discovered that the API server has been remarkably busy with API requests from a couple places in Europe over the past 3 days or so.  As these requests become fewer, you should notice improved query times.  Please let us know if this is not the case.
