### ISSUE TITLE
Error while running LDtrait

### ISSUE THREAD

**Issue by vermaa1** [CBIIT/LDlinkR#19]
Hi,

I am getting an error with the LDtrait function. 
```
mytrait<-LDtrait(snps = "rs334",
                 pop = c("YRI"),
                 r2d = "r2",
                 r2d_threshold = "0.1",
                 win_size = "500000",
                 token = "MY TOKEN"
                )

Error in LDtrait(snp = "rs334", pop = "YRI", r2d = "r2", token = "MY TOKEN") : 
  integer(0) integer(0) integer(0) integer(0) integer(0) numeric(0) numeric(0) integer(0) numeric(0) integer(0) numeric(0)
```

Thanks!

**Comment by timyers** [comment]
Thank you for reporting this issue.  After investigating, I determined you uncovered a bug that is triggered when the LDtrait response data from the API contains the GWAS trait "Refractive error", as your query variant did.  I am working on a fix and will report it here when it's available.  Thank you for your interest in LDlinkR.

**Comment by timyers** [comment]
The patch to fix this issue is now available on Github and will be included in the next version submitted to CRAN.
Thank you again for reporting this problem.

**Comment by vermaa1** [comment]
Thank you so much! It works now.
