### ISSUE TITLE
LDproxy_batch

### ISSUE THREAD

**Issue by cs16436** [CBIIT/LDlinkR#23]
Hi,

I've been using LDproxy_batch, which is an excellent tool! When I previously used this, the outputs included a column 'query_snp'. I've noticed that recent outputs no longer include this column: 

Function	RS_Number	Coord	Alleles	MAF	Distance	Dprime	R2	Correlated_Alleles	FORGEdb	RegulomeDB

Please may I check that this column is no longer included (or if there may be an issue with my outputs)? 

Thank you very much in advance!

**Comment by timyers** [comment]
Hello,

Thank you for reaching out and thanks for your interest in LDlinkR.  I ran a test and my output includes the 'query_snp' column.  Here's the example:

`LDproxy_batch(snp = c("rs114", "rs127"),
              token = Sys.getenv("LDLINK_TOKEN"),
              append = TRUE,
              genome_build = "grch38"
)`

We did have an issue a while back with columns in the output from LDproxy but we were able to fix it.  Are you using the latest version of LDlinkR, v1.2.3?  If not, please update and try again.  Also, the 'query_snp' column is only added to the output file when 'append = TRUE'.  If you are still having trouble, please provide us with a reproducible example of your code and I'll try to provide additional help.

Kind regards,
Tim

**Comment by machiela** [comment]
Thanks, Tim!
Mitch

**Comment by cs16436** [comment]
Hi Tim,

Thank you so much for your help - installing the latest version of LDlinkR did fix this.

Best wishes, Chloe

**Comment by timyers** [comment]
That's great news!  Glad we were able to help.
Best of luck with your research.
Regards,
Tim
