### ISSUE TITLE
Error in LDproxy： Bad Gateway (HTTP 502)

### ISSUE THREAD

**Issue by xdreame** [CBIIT/LDlinkR#24]
Hi
Recently, when i used LDproxy_batch in a R script, there would be an error as following:
      _Error in LDproxy(snp = snp[i, ], pop = pop, r2d = r2d, token = token,  : 
      Bad Gateway (HTTP 502)._
I have changed the token, but it didn't work.
Could you please provide some suggestions to help me out? 
Thank you.

**Comment by AnnabelHE627** [comment]
Hi, I am facing the same issue in using LDproxy_batch from yesterday. Do you have any suggestions to resolve this? Thank you.

**Comment by timyers** [comment]
Can you provide us with more information?  Are your `LDproxy_batch` requests large?  LDproxy uses a lot of resources.  More information will help us provide suggestions.

**Comment by Xenophong** [comment]
same for me unfortunately... with only one variant.

**Comment by AnnabelHE627** [comment]
> 
My LDproxy_batch requests the data of several lists of variants, and it works smoothly in the past. However,  it doesn't work even if I only request for only one variant these days.

**Comment by timyers** [comment]
Thank you for bringing this issue to our attention.  This issue has been resolved.  Additional resources to handle higher volumes of traffic were added to the server.
