### ISSUE TITLE
Gateway Timeout (HTTP 504)

### ISSUE THREAD

**Issue by Yunqihuang971116** [CBIIT/LDlinkR#28]
Hi,
When I calculate LD matrix I get this error:
> LDinfo <- LDmatrix(snps = rsid$`rownames(betas)`, 
+                    pop = "EUR", r2d = "r2", 
+                    token = "3cc36f1d69be", 
+                    file =FALSE)

LDlink server is working...

Error in LDmatrix(snps = rsid$`rownames(betas)`, pop = "EUR", r2d = "r2",  : 
  Gateway Timeout (HTTP 504).
Could you please help deal with it?
Yunqi

**Comment by timyers** [comment]
Hi Yunqi,

Apologies for the delayed response.  Are you still getting the 504 error?  I have not been able to replicate it.  Your code looks correct but I cannot replicate it exactly without the SNPs you used.  However, the code below is working for me.  Please try again and let us know if you're still getting the error.

LDinfo <- LDmatrix(snps = c("rs3", "rs4", "rs148890987"), 
                                 pop = "EUR", 
                                 r2d = "r2",
                                 token = Sys.getenv("LDLINK_TOKEN"), 
                                 file = FALSE
                                )

Kind regards,
Tim

**Comment by Yunqihuang971116** [comment]
Hi Tim,

It worked after I changed a network!
Thanks so much!

Yunqi



---- Replied Message ----
| From | Tim ***@***.***> |
| Date | 10/11/2023 21:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [CBIIT/LDlinkR] Gateway Timeout (HTTP 504) (Issue #28) |

Hi Yunqi,

Apologies for the delayed response. Are you still getting the 504 error? I have not been able to replicate it. Your code looks correct but I cannot replicate it exactly without the SNPs you used. However, the code below is working for me. Please try again and let us know if you're still getting the error.

LDinfo <- LDmatrix(snps = c("rs3", "rs4", "rs148890987"),
pop = "EUR",
r2d = "r2",
token = Sys.getenv("LDLINK_TOKEN"),
file = FALSE
)

Kind regards,
Tim

**Comment by timyers** [comment]
I'm glad it worked for you.
Tim
