### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    Timeout was reached: [ldlink.nih.gov] SSL/TLS connection timeout

### ISSUE THREAD

**Issue by RochelleKnight** [CBIIT/LDlinkR#30]
Hi,

I am trying to use LDproxy_batch to get proxy SNPs. This has worked in the past however recently I am getting the error message 

```
Submitting request for query variant rs4442317.
Checking status of server...Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [ldlink.nih.gov] SSL/TLS connection timeout'
```
LDproxy_batch briefly worked the other day however is now not working again. Do you know if there is a server issue or if there is something I can do to fix this?

Thanks in advance :)

**Comment by timyers** [comment]
Hi,

The following simple function call just worked for me:

LDproxy_batch(snp = c("rs114", "rs127"),                            
              token = Sys.getenv("LDLINK_TOKEN"),
              append = FALSE
)

The server is working on my end.  I recommend waiting for a short period of time and try again.  Perhaps there's a network issue between you and the server causing the timeout.  If the problem persists, please post here again to let us know.

Tim
