### ISSUE TITLE
LDmatrix Timeout 

### ISSUE THREAD

**Issue by ljmills** [CBIIT/LDlinkR#35]
I am getting a timeout error running LDmatrix with ~1400 SNPs. It is working fine for smaller (< 800 SNPs) queries. 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached [ldlink.nih.gov]: Operation too slow. Less than 1 bytes/sec transferred the last 600 seconds

test <- LDmatrix(snps = tmp$ldSNP,
                   pop = "AFR",
                   token = "52857146c26a",
                   r2d = "r2",
                   file = paste0(name, "_r2Matrix.txt"),
                   genome_build = "grch38_high_coverage")

**Comment by timyers** [comment]
Hi, 
Thanks for sharing the code.  Could you also provide the list of variants you are interested in?
Thank you.

**Comment by ljmills** [comment]
[7_50407233_forLDmatrix_withChr.txt](https://github.com/user-attachments/files/17982961/7_50407233_forLDmatrix_withChr.txt)
[5_111791133_forLDmatrix_withChr.txt](https://github.com/user-attachments/files/17982964/5_111791133_forLDmatrix_withChr.txt)


Both of these lists of SNPs is failing. I am using the ldSNP column

**Comment by timyers** [comment]
I'm experiencing the timeout error as well when the query takes > 10 min.  I'll email the LDlink team leads for the server and make enquires.  Stay tuned....

**Comment by timyers** [comment]
I understand you're in contact with someone else on our team via the LDlink email listserve and they are helping you.  Please let me know if this is not correct.  They suspect the server is experiencing a lot of traffic currently causing the server to take longer than usual to perform calculations.  As of late yesterday afternoon, they are working to confirm.  Hopefully things will improve today.

Thanks for your interest in LDlink and LDlinkR!
